### ISSUE TITLE
Using `source-ref` to create the PR

### ISSUE THREAD

**Issue by kameshsampath** [gitops-tools/image-updater#4]
When using this tool with tekton triggers, the triggers usually rely on the GitHub `${body.head.commit.id}`, and the tool expects the `source-branch` to be the name of the branch. It will be nice to have `source-ref` as well to create PR.

**Comment by bigkevmcd** [comment]
@kameshsampath Just summarising our out-of-GitHub discussion, we need the source-branch to be able to create a PR as the source-branch to base the PR from.

I don't think you can create PRs off of commit IDs.

**Comment by kameshsampath** [comment]
Thanks Kev, I understand now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
